name: workflow.yml
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  BASE_IMAGE_NAME: ${{ vars.BASE_IMAGE_NAME || github.repository }}-base

jobs:
  build:
    runs-on: [ self-hosted ]
    permissions:
      contents: read
      packages: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build maven modules
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: 'maven'
      - run: |
          sh build.sh
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: 'true'
          tags:
            ${{ steps.base-meta.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}:pkg-${{ steps.check-rebuild.outputs.package-hash }}
